### ISSUE TITLE
Build tensorspace as CommonJS module

### ISSUE THREAD

**Issue by BoTime** [tensorspace-team/tensorspace#189]
### Goal:

Use tensorspace in Node.js with `require()` syntax

**Comment by BoTime** [comment]
1. Refactor source code (add `import * as THREE from 'three'`)

2. Two input files:
- tensorspace.js -> tensorspace.cjs.js
- tensorspace.dev.js -> tensorspace.dev.cjs.js

**Comment by syt123450** [comment]
For threejs, added:
```javascript
import * as THREE from "three";
```

For tfjs, added:
```javascript
import * as tf from "@tensorflow/tfjs";
```

For tween.js, added:
```javascript
import * as TWEEN from "@tweenjs/tween.js";
```

For Stats.js, added:
```javascript
import Stats from "stats.js/src/Stats";
```

For trackballcontrol, added:
```javascript
import TrackballControls from "three-trackballcontrols";
```

**Comment by txmxthy** [comment]
> For threejs, added:
> 
> ```js
> import * as THREE from "three";
> ```
> 
> For tfjs, added:
> 
> ```js
> import * as tf from "@tensorflow/tfjs";
> ```
> 
> For tween.js, added:
> 
> ```js
> import * as TWEEN from "@tweenjs/tween.js";
> ```
> 
> For Stats.js, added:
> 
> ```js
> import Stats from "stats.js/src/Stats";
> ```
> 
> For trackballcontrol, added:
> 
> ```js
> import TrackballControls from "three-trackballcontrols";
> ```

Hi, I'm trying to use tensorspace to visualize one of my projects within a page on my website which is using next js and I'm having some trouble with importing the dependencies.

Is there a way to do the imports like this in js rather than with the script tags? I've tried variations of both without much luck - might end up just embedding a codepen 😎
